-- TODO: create the tasks table for Week 07.
-- Required columns:
--   id TEXT PRIMARY KEY
--   title TEXT NOT NULL
--   description TEXT
--   status TEXT with CHECK ('pending', 'in_progress', 'done')
--   created_at TEXT
--
-- Add an index that helps status-based queries.
